### ISSUE TITLE
reference list of trustable DNS-over-TLS servers

### ISSUE THREAD

**Issue by monperrus** [getdnsapi/stubby#108]
I'm looking for a reference list of DNS-over-TLS servers that we can trust. I would create my stubby configuration from it. 

There is a list of servers at https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Test+Servers
 but it's about "test" not about "trust".

Is there a reference list of trustable DNS-over-TLS servers? Where should we create one?

**Comment by ArchangeGabriel** [comment]
Trust is a personal matter. EOL.

That being said, this list is a good start, especially the first section since you are already trusting those people code and the second section if you believe in Quad9/Cloudflare commitments. I also use some servers of the third section, because I only use port 443 and need a bit more variety in my upstreams.

However, this will be way better when Oblivion DNS will be a thing, and everyone will be using DNSSEC, cause trust would matter way less then.

**Comment by saradickinson** [comment]
I agree that trust is hard to define and is different for each individual, which is why the current page just tries to provide information for users to make their own decisions. The current page tries to group them based on logging policy or link to their logging policy page - thats about all we can do for now.

I am separately involved in this document https://tools.ietf.org/html/draft-dickinson-bcp-op-00 one of the goals of which is to provide a way for users to decide which servers they trust and to encourage independent reporting and assessment of server operators.

**Comment by monperrus** [comment]
I agree that "trustable" depends on the context. 

https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Test+Servers is a great page. What's confusing to me is the "test" in the URL and the page title.

Would it be an option to rename it in "DNS Privacy Servers" or even better "DNS-over-TLS Server List"?

**Comment by saradickinson** [comment]
Agree it should be updated... I'm planning to re-work this page (possibly splitting it up), separate out Quad9 and Cloudflare and add DOH servers but I will at least keep the page with this link in some form because the link to it (which contains the name) has been used in so many presentations and announcements!

**Comment by monperrus** [comment]
> I'm planning to re-work this page (possibly splitting it up)
Excellent, looking forward to it! Thanks.

**Comment by saradickinson** [comment]
Wow - thanks for spotting this - fixed

**Comment by demetry14** [comment]
CleanBrowsing literally owns the world's fastest resolver and yet not on the list.
