### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by awgcooper** [getdnsapi/stubby#116]
Hi there.  I'm trying to get the latest stubby git checkout running on Ubuntu 18.04.  I ran configure as follows:
./configure --without-libidn --enable-stub-only --with-ssl --enable-debug-stub --with-stubby

The config file was left unchanged in "/usr/local/etc/stubby".  I initiated the daemon with "stubby -v" and received the following message:

"stubby: error while loading shared libraries: libgetdns.so.10: cannot open shared object file: No such file or directory".  Not surprisingly, there was nothing in the syslog.

I've seen these messages before and usually it requires playing around with symlinks or moving actual files.  However this time it's simply "libgetdns.so.10" solely residing in "/usr/local/lib" symlinked to "libgetdns.so.10.0.2" which is also in the same dir (and "libgetdns.so" is also symlinked to the same file).

Any suggestions please?

**Comment by wtoorop** [comment]
@awgcooper Hi, you either have to install on a path which is searched by your ld.so, i.e. `configure`  with a `--prefix=/usr` option, or add `/usr/local` to the search path of ld.so, either by adding a file (with the path) to the `/etc/ld.so.conf.d` directory and then running `ldconfig`, or by making sure `/usr/local/lib` is part of the path list of the `LD_LIBRARY_PATH` environment variable.

I'm closing the issue because it is a generic configure question and is not stubby specific.
