### ISSUE TITLE
featue-request: more clear 'reapply' 127.0.0.1/::1 button for wifi rebinds 

### ISSUE THREAD

**Issue by geeohgeegeeoh** [getdnsapi/stubby#117]
here in china I'm having to re-bind to wifi or LAN in hotel bedroom pretty frequently, so the re-apply to get DNS 127.0.0.1/::1 is a frequent operation.

There is absolutely no "barrier" to doing this in the stubby GUI right now, Its just that its not an occasional thing: some kind of "reapply" function to just reset the godsdamn binding would help because each DHCP rebind I seem to lose config, if I transit across physical device, or from a foreign wifi back into one I was on before.

**Comment by saradickinson** [comment]
When you say re-bind what do you meant exactly? Is it that you have to manually disable Stubby to access a captive portal or are you just re-joining the network after being kicked off and DHCP is overwriting your resolv.conf entries?  IFAIK with macOS (I assume this because you have mentioned the GUI) if you have manually specified the DNS server then this should not be overwritten just by re-joining a network....

I'm not saying we shouldn't be doing a better job of detecting changes to the system resolver settings by other processes and offering a re-apply/override option (we should!), I'm just trying to understand your specific issue.

**Comment by geeohgeegeeoh** [comment]
It "feels" like when I either have to rebind to the wifi, or get moved
between wifi bindings, or from LAN to wifi, I have to re-open stubby to
re-commit the override of DNS to 127.0.0.1

Once I have given stubby "permission" to put me on a local DNS, I feel I
shouldn't have to re-commit: It should be policing it, and keeping it up to
date.

If (and yes, this is on OSX) there is a credentials issue and it can't do
it without permission, I guess there isn't much you can do. I run multiple
desktops, so it has additional cost of driving to the screen stubby is on,
to recommit. From a UX/UI consideration, the buttons are a bit 'all over
the place' for this.

I have a tickbox, and the revert/apply pair, and another revert to
default.  Two reverts? Confusion! Revert to default and 'tick this box to
use stubby' Feel like they do the same thing too.

**Comment by geeohgeegeeoh** [comment]
Actually, I think you should close this one. It doesn't have a clear moment
of a thing you can do, and its not clear or well proven. There are good
signs this is PBCK on my part.

-G

**Comment by saradickinson** [comment]
Thanks for the notes. I'm going to leave this open because it does raise 2 issues we should look at
1) Notifying the user when the system config changes
2) Improving the UI design to make re-applying easier

**Comment by saradickinson** [comment]
Reviewing older issues and closing this one because of age. Note that we are working on a newer GUI interface that should do a better job of handling this situation: https://dnsprivacy.org/wiki/display/DP/Stubby+Manager+GUI
