### ISSUE TITLE
How to use Stubby? (non-technical request)

### ISSUE THREAD

**Issue by baimafeima** [getdnsapi/stubby#160]
I have stubby installed via the repository of a Linux-based operating system. What now? How to use it and how to check that it does what it is intended to do? Reading the configuration site was way too complicated. I'm looking for easy, non-technical information for an average user. Many thanks. 
PS: When can we expect a GUI?

**Comment by saradickinson** [comment]
The best documentation we have at the moment is on this page: https://dnsprivacy.org/wiki/pages/viewpage.action?pageId=3145786 
but is is for a technical user.....
But also try reading this nice blog article:
https://www.linuxbabe.com/ubuntu/ubuntu-stubby-dns-over-tls

I do think we need a GUI for non-technical users, we have a prototype one for macOS, but nothing for linux. Unfortunately we don't have the resources to work on that right now but we hope to in the near future.

**Comment by insideTheFlux** [comment]
@saradickinson I followed this link: https://www.linuxbabe.com/ubuntu/ubuntu-stubby-dns-over-tls

However, I don't know if anything is really working. Ubuntu 18.04 here, running a personal recursive resolver.

I have:
_resolution_type: GETDNS_RESOLUTION_STUB_
_dns_transport_list:
  - GETDNS_TRANSPORT_TLS_
_tls_authentication: GETDNS_AUTHENTICATION_REQUIRED_
_listen_addresses:
  - 127.0.0.1
  -  0::1_
_round_robin_upstreams: 1_

All upstream_recursive_servers are commented out. I've 'tcpdump -w file.pcap -i eth0' viewed the file with Wireshark but I'm still not sure if its encrypted. How can I confirm?

thanks.

**Comment by saradickinson** [comment]
Couple of comments here:
1) I assume that you mean you have a local recursive resolver that is configured via DHCP on you local machine and that resolver supports DoT?
2) Which will work but....If you don't have any upstreams specifically configured then you can only do Opportunistic TLS (since there are no credentials specified for the server). In which case you should use:
`tls_authentication: GETDNS_AUTHENTICATION_NONE`
which will use TLS but not authenticate the connection. If you want to do Strict DoT to your local resolver you'll have to configure an authentication name in stubby.
2) Once you have made this change then try
`tcpdump -n -w file.pcap -i eth0 port 853` 
any traffic you see with this command will be encrypted.]

Hope this helps!

**Comment by saradickinson** [comment]
I'm closing this as there hasn't been a response in several weeks. Please re-open if you have further questions.
