### ISSUE TITLE
Generic error

### ISSUE THREAD

**Issue by thb007** [getdnsapi/stubby#175]
#        value: wTeXHM8aczvhRSi0cv2qOXkXInoDU+2C+M8MpRyT3OI=
, "Generic error"
Error parsing config file "/usr/etc/stubby/stubby.yml": Generic error
WARNING: No Stubby config file found... using minimal default config (Opportunistic Usage)
Not starting because a running stubby was found on pid: 3972
root@linaro-alip:/home/linaro# dig @127.0.0.1 baidu.com

; <<>> DiG 9.10.3-P4-Debian <<>> @127.0.0.1 baidu.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 11839
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;baidu.com.			IN	A

;; Query time: 3 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Apr 10 00:24:44 CST 2019
;; MSG SIZE  rcvd: 27

**Comment by thb007** [comment]
[stubby.zip](https://github.com/getdnsapi/stubby/files/3060031/stubby.zip)

**Comment by saradickinson** [comment]
Your problem is that the config file is not formatted correctly - YAML is sensitive to whitespace - the text MUST be aligned correctly for the file to be parsed. I have attached a corrected version of your config file (with a txt suffix so GitHub will accept it!). 
[stubby_fixed.yml.txt](https://github.com/getdnsapi/stubby/files/3068050/stubby_fixed.yml.txt)
