### ISSUE TITLE
Stubby doesnt' work on Linux Mint

### ISSUE THREAD

**Issue by 480gh8q0hg08** [getdnsapi/stubby#176]
I've been trying to get stubby to to work on my system with no luck. I followed the guide for ubuntu (https://www.linuxbabe.com/ubuntu/ubuntu-stubby-dns-over-tls) When i try to connect to the internet nothing happens

Below are some screenshots throughout my process. I didn't mess around with the config file.

systemctl status stubby

![Selection_002](https://user-images.githubusercontent.com/49598754/56085690-dbc6e200-5e36-11e9-95f7-2149198c2405.png)

sudo netstat -lnptu | grep stubby

![Selection_003](https://user-images.githubusercontent.com/49598754/56085691-e84b3a80-5e36-11e9-8855-075dfd9cc000.png)

sudo netstat -lnptu | grep systemd-resolve

![Selection_004](https://user-images.githubusercontent.com/49598754/56085696-ff8a2800-5e36-11e9-9027-7ec88b196a51.png)

My network settings

![Selection_005](https://user-images.githubusercontent.com/49598754/56085697-05800900-5e37-11e9-8378-0100bd860a4b.png)

Just looking at my screenshots and the ones on the guide I'm following it seems like there are some differences despite typing in the same commands, but I'm not sure what I did wrong. Any help would be much appreciated.

Thanks!

**Comment by saradickinson** [comment]
Hi there, 

I wonder if this is your problem  since your screenshot shows that stubby is only listening on UDP (quoting from the webpage) "Note: If dnsmasq is listening on TCP port 53 of 127.0.0.1, then Stubby will listen only on UDP port 53 of 127.0.0.1." Try looking at the output of
`sudo netstat -lnptu | grep dnsmasq` - you probably need to disable dnsmasq or you could use different IP address for stubby e.g. 127.0.0.2


Also - it seems you only have IPv4 on your machine (or have only configured stubby to listen on IPv4), so you won't see the IPv6 output that is shown in the webpage for `sudo netstat -lnptu | grep stubby`  e.g. stubby listening on udp6/tcp6 on ::1:53.  

Hope this helps!

**Comment by 480gh8q0hg08** [comment]
Thank you! That seems like a critical step missing from that tutorial! I got it to work now.
