### ISSUE TITLE
systemd: make stubby restart after it crashes

### ISSUE THREAD

**Issue by appliedprivacy** [getdnsapi/stubby#191]
When stubby crashes due to a bug, systemd will not start it again.

Lets add

Restart=on-failure

to the systemd service file to make stubby recover automatically in such situations.

**Comment by ArchangeGabriel** [comment]
@wtoorop @saradickinson This seems a good idea to me. Any objection?

**Comment by jhamberg** [comment]
Sounds good to me. I think this should also be possible through Task Scheduler:

1) Create a new trigger
2) Select "On an event" from the dropdown menu
3) Click on the "Custom" radio button and press "New Event Filter..."
4) Select the "By log" radio button and choose "Windows Logs > Application"
5) In the Includes/Excludes Event IDs box, enter 1000 (for Application Crash)

I have not tried this trigger before, will report back if it works.

**Comment by saradickinson** [comment]
https://github.com/getdnsapi/stubby/commit/7856e52363c1823475dcf332589e4db35b9fed60

**Comment by Mikesco3** [comment]
I'm having an issue on Arch, where I have to always restart the stubby service after logging in, in order to get DNS working.

Just in case, I'm running dnsmaskl, and I'm using primarily a wifi connection, I haven't tested if the issue also occurs over ethernet connection.

I've tried just restarting NetworkManager, but that doesn't fix the problem, the only thing that fixes internet browsing is to restart stubby and then DNS resolves. I usually don't have to do it again until I reboot.

I'm running stubby as a systemd service.

**Comment by saradickinson** [comment]
Closing as fixed in 0.3.0
