### ISSUE TITLE
Powershell scripts work only on Windows 8+

### ISSUE THREAD

**Issue by ArneBachmann** [getdnsapi/stubby#31]
As explained [here](https://stackoverflow.com/questions/27213562/powershell-get-netadapter-command-not-recognized).
```
Get-NetAdapter : Die Benennung "Get-NetAdapter" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des
Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
In C:\Program Files\Stubby\stubby_setdns_windows.ps1:1 Zeichen:1
+ Get-NetAdapter -Physical | ForEach-Object {
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-NetAdapter:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by saradickinson** [comment]
Yes, sorry at the moment we are only supporting Windows 8 and 10.

**Comment by Velocet** [comment]
Hi there, since i couldn't find the PoSh script on GitHub i have to post this here. This version should work on systems with XP and up since it relies on WMI instead of cmdlets:

```PowerShell
#Get enabled/connected adapters (same as 'Get-NetAdapter -Physical')
$NetworkAdapters = Get-WmiObject -Class 'Win32_NetworkAdapterConfiguration' -Filter {IPEnabled = 1}

#Verbose output so the user gets to know the current configuration
Write-Output -InputObject 'Found Adapters:'
$NetworkAdapters | Format-Table -Property IPAddress,DefaultIPGateway,DNSServerSearchOrder,Description

Write-Output -InputObject  'Setting DNS entries to use Stubby if it is running:'
#Change the DNS entry for each found network adapter
foreach ($NetworkAdapter in $NetworkAdapters) {
  Write-Output $NetworkAdapter.Description
  $NetworkAdapterConfig.DNSServerSearchOrder = '127.0.0.1','1::0'
}
```

----

Taken from here [Windows installer for Stubby](https://dnsprivacy.org/wiki/display/DP/Windows+installer+for+Stubby):

> **Known Issues**
> * We are aware of occasional issues when Windows sleeps and resumes when stubby must be restarted to work correctly.

From my point of view there are two options: rewrite some parts so that stubby could be used as a service (best solution) or make use of the "Task Scheduler" that comes with Windows. It's possible to create a task that get's triggered (and starts stubby or checks for it) every time the computer is woken up, resumes or boots.

----

I also think it's better to only have one Wiki/Issue Tracker/Comment section. There are a lot of comments in the Wiki (eg [Configuring Stubby](https://dnsprivacy.org/wiki/display/DP/Configuring+Stubby)) that will never make it here.

(sorry for abusing this issue...)

**Comment by saradickinson** [comment]
The script was in PR #23, which I have just merged. Thanks for the alternative though. 

I've created a separate issue #37 for the scheduled task enhancement which we'll add to the next release of the installer. 

And please continue to create issues here - I'm trying to track comments on the wiki and create issues as needed. I don't want to ban comments on the website, but will add a page footer with a link to this issue tracker to make it clearer.

**Comment by Velocet** [comment]
Well.. it's not an alternative, it's an improvement/bugfix since it works on Windows 7? (at least the script) 🌝

**Comment by saradickinson** [comment]
Closing this issue as release 0.2.0 of stubby and the latest Windows installer contained alternative scripts to be used on Windows 7 (with issues i.e. no IPv6 support)
