### ISSUE TITLE
Extend wiki info about manual configuration on Windows

### ISSUE THREAD

**Issue by ArneBachmann** [getdnsapi/stubby#35]
![stubby](https://user-images.githubusercontent.com/20544098/32277839-0dabfc6a-bf14-11e7-9450-ad2f9225b0b1.png)

**Comment by saradickinson** [comment]
The issue with this is that if none of the privacy servers are available the system will fall back to the alternate which does not provide DNS privacy. This is OK if the user want Opportunistic Privacy, but not if they want strict privacy. We've been thinking it would be better to include the default DNS servers in the Stubby config (but preferentially use servers that provide privacy) if the user wants opportunistic which would also solve this problem.

**Comment by Velocet** [comment]
Can somebody please explain to me what the problem is? The second DNS server which acts as a fallback when the local one (stubby) doesn't respond?

**Comment by saradickinson** [comment]
These settings control where the system sends DNS queries over UDP. By sending all queries to 127.0.0.1 they are all directed to Stubby which receives them over UDP on localhost and then sends then out over the network using TLS. Having an alternate server listed means that if there are problems with responses to 127.0.0.1 then DNS queries will go over UDP over the network to the alternate server and they won't be private. 

The default Stubby file uses 'Strict' mode which means if Stubby can't get an authenticated TLS connection to a DNS server it won't send DNS queries because they won't be private. 
Stubby can also be configured to be in  'Opportunistic' mode which tries to get an authenticated TLS connection but if it can't it will send DNS queries over UDP or TPC (clear text) in order to get DNS responses (because without DNS there isn't much you can do). This is a choice for the user, depending on how critical it is that they DNS messages are encrypted. 

Having an alternate server would bypass the 'Strict' setting of Stubby.

**Comment by ArneBachmann** [comment]
Well, actually this issue was just about *extending the documentation* on how to set the DNS addresses on Windows, because it took me some time to find out and create the supporting screenshot, while the approach wasn't clearly lined out in the wiki.

Sara then mentioned, that having alternative DNS resolvers compromises (strict) security, which is correct but something I'm fine with, as DNS must be available even before stubby is started during system boot, especially when on corporate networks...

**Comment by saradickinson** [comment]
OK - many thanks for the screenshot I understand now! I've added it to the page and also some text about Opportunistic mode and alternate servers. Hope this helps?

**Comment by ArneBachmann** [comment]
Great! Hope it helps others as well.
