### ISSUE TITLE
Experience dropouts from time to time on macOS High Sierra

### ISSUE THREAD

**Issue by MindTooth** [getdnsapi/stubby#74]
Hi,

I'm using Stubby on High Sierra, and at least once a day I experience that I'm unable to resolve DNS.  When pinging `8.8.8.8` I get a connection.  Have yet to change to a different DNS to eliminate stubby, but I did not have this issue with DNSCrypt – nor regular DNS.

I run with default config (strict mode I believe), and I use the Homebrew package.

Any thoughts?

**Comment by saradickinson** [comment]
Hi there, I haven't come across this before. Do you see anything in the logs when you have the problem? They should be in
```
/usr/local/var/log/stubby/stubby.log
```
Also, it might be worth adding Quad9 to your configuration (9.9.9.9, "dns.quad9.net") as they have an anycast service and you should get directed to their local POP. All the default servers are located in the Netherlands and you might be getting timeouts if your RTT is large.

**Comment by MindTooth** [comment]
Gist: https://gist.github.com/MindTooth/ccf8179a54daddcef3b0fca8aad9171a

I have a lot of failures.  Even though I've got internet access.

**Comment by MindTooth** [comment]
Happened again: https://gist.github.com/MindTooth/90b424d6beca87d820e4d95b6cbccea4

**Comment by saradickinson** [comment]
Thanks - does the problem persists when you re-start the stubby service or is it fixed?
```
brew services restart stubby
```
Would you be able to grab a short packet capture when the issue occurs with Wireshark or tcpdump? 
```
tcpdump -i en0 port 853 -n  
```

**Comment by MindTooth** [comment]
Didn’t restart last time.  But the previous times a tried restarting several times.  And still no go.

I’ll test det command when I get home.

**Comment by saradickinson** [comment]
Also try this command to see if you can reach 9.9.9.9 on different transports when the issue occurs. UDP query
```
getdns_query -s @9.9.9.9 example.com -V -q
```
TLS query
```
getdns_query -s @9.9.9.9 example.com -V -q -L
```

**Comment by MindTooth** [comment]
https://gist.github.com/MindTooth/d407f86bb957e89903f7e989f0911f57

Remembered only the one command, and since the internet dropped, I couldn't open this page.  I'll save the command now.

**Comment by saradickinson** [comment]
Thanks for the logs.... looking at this it doesn't seem to be an issue with Stubby - it seems to be retrying servers correctly when it can't reach them. As far as I can tell it seems that during this time period the servers are just taking a long time to respond which leads to either the TCP handshake failing with a timeout, or the requests failing with a timeout. That makes me think it is a network/connectivity issue of some kind, possibly specific to TLS or port 853 if you can ping 8.8.8.8 when Stubby is failing. 

So, some other things to try to diagnose the issue:
- adding more servers to your existing config OR
- using an Opportunistic profile instead of Strict. To do this
1) comment out this line in the config:
```
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
```
2) Change your transports to look like this:
```
dns_transport_list:
  - GETDNS_TRANSPORT_TLS
  - GETDNS_TRANSPORT_UDP
  - GETDNS_TRANSPORT_TCP
```
Opportunistic isn't as strong for privacy as Strict, but it means Stubby will fall back to cleartext if it can when TLS isn't available so at least you get DNS resolution. Both 9.9.9.9 and 185.49.141.37 provide service over UDP/TCP.

**Comment by MindTooth** [comment]
Some more data.  I'll test by going down the opportunistic route.

https://gist.github.com/MindTooth/74496a6e5621a71184442dc2e73e80b1

**Comment by MindTooth** [comment]
I'll be closing this for now.  Seems to be working okay for the moment.

Thanks for sticking with me 👍

**Comment by MindTooth** [comment]
Seems that I still have some drops when accessing new sites.  Tried 1.1.1.1 for about a week now, but reverted back to the default conf file.

Also added DNSMasq for caching today.  Reason for me posting again, is that I were unable to load a new domain.

I will try for a period of time to have no extra layers on my DNS/internet to check if this occurs on lower layers.

**Comment by saradickinson** [comment]
I've recently learned that 1.1.1.1 is now using a short idle timeout which can cause Stubby to think the server is unavailable - see https://github.com/getdnsapi/stubby/issues/105. Try using  ```idle_timeout: 5000``` for now to see if that improves things with 1.1.1.1.

**Comment by MindTooth** [comment]
Been using `cloudflared` & `dnsmasq` for the past two/three weeks, and have had no dropouts.

I'll change back to `stubby` and test this once again with the new version.
