### ISSUE TITLE
EDNS should not be passed through to client

### ISSUE THREAD

**Issue by twisteroidambassador** [getdnsapi/stubby#98]
It looks like Stubby passes the entire DNS response from the upstream server to the client, including the OPT pseudo-RR which specifies EDNS options. 

(I discovered this by having multiple upstream servers configured with round-robin, and retrying the same request, observing different EDNS options being returned each time. [See here for results of repeated `dig` command](https://pastebin.com/zgxf2w8k), and [here for corresponding Stubby log](https://pastebin.com/gMCqDG9k). 

In particular, one of the responses has an option (`OPT=11: 01 2c (".,")`) stating that the DNS server is willing to allow a long-lived TCP connection with a 30-second timeout, which Stubby is certainly not honoring.)

[RFC 6891 - Extension Mechanisms for DNS (EDNS(0))](https://wiki.tools.ietf.org/html/rfc6891) states:

>    EDNS is a hop-by-hop extension to DNS.  This means the use of EDNS is
>    negotiated between each pair of hosts in a DNS resolution process,
>    for instance, the stub resolver communicating with the recursive
>    resolver or the recursive resolver communicating with an
>    authoritative server.

And:

>    OPT RRs MUST NOT be cached,
>    forwarded, or stored in or loaded from master files.

So, it might be a good idea to strip out the OPT RR from upstream responses before passing through to the client. 

(Optionally, Stubby may add its own OPT RR in accordance to its capabilities: perhaps UDP responses larger than 512 bytes, or long-lived TCP connections?)

**Comment by saradickinson** [comment]
Interesting and good catch... I  completely agree that we should fix this as it is an error in the implementation. It is mentioned in passing in [Keepalive spec](https://tools.ietf.org/html/rfc7828#section-4) , but is under-specified if you ask me (and was an author  :-)  ). I don't think it is mentioned at all in the padding spec. Note that in [the DSO spec](https://tools.ietf.org/html/draft-ietf-dnsop-session-signal-07#section-4.1.3), there is a specific recommendation that those messages are NOT forwarded blindly. 

I would also actually argue that stubby is not a 'Middlebox that simply forwards requests'  and it is probably not a pure proxy by the RFC6819 definition and we should be more careful in using that phrase. Since there are a multitude of setting (DNSSEC, transport, etc.) that effect how stubby handles DNS resolution I think it  more like an 'intelligent DNS forwarder'.  

Note that the [DNS terminology draft bis](https://tools.ietf.org/html/draft-ietf-dnsop-terminology-bis-09) is still quite vague on what a proxy or forwarder actually is! I'm minded to think that RFC5625 should be bis-ed to clarify this, particularly since the picture with respect to transport for DNS has changed so much !

**Comment by wtoorop** [comment]
@saradickinson Ok sorry, won't call it that anymore then ;)

**Comment by saradickinson** [comment]
@wtoorop I've used it _repeatedly_ in presentations and just fixed a couple of instances on dnsprivacy.org so it was a 'Note to self:' as much as anything! 😁

**Comment by wtoorop** [comment]
Fixed in the 1.4.2 release
